### ISSUE TITLE
Bug #1: Make a card go *poof*

### ISSUE THREAD

**Issue by ZWORX52** [ericx1e/24#1]
Here is how you recreate this bug. 
1. Select a card. Here, the "4" is selected.
![image](https://user-images.githubusercontent.com/66217856/135936199-219b8266-01b6-4908-9310-e56f3a7892ec.png)
2. Click the "n" key to generate a new card set.
![image](https://user-images.githubusercontent.com/66217856/135936244-809cdf71-cee3-4965-b666-03405cd2fea6.png)
3. Select another card, the card that should go *poof*.
![image](https://user-images.githubusercontent.com/66217856/135936321-b84f7e9e-04dc-4408-af77-84efd1c47a7a.png)
4. Finally, initiate any of the operations. That card that you just selected? It's gone now.
![image](https://user-images.githubusercontent.com/66217856/135936350-e6d5c225-ec3c-439d-8376-156c73b5e9f3.png)

**Comment by ericx1e** [comment]
All fixed now. Thanks for bringing it up!
