### ISSUE TITLE
Bug #2: Wait... Those aren't valid cards!

### ISSUE THREAD

**Issue by ZWORX52** [ericx1e/24#2]
This bug deals with the lack of checking when doing operations on cards. It is quite simple; let me walk you through.
1. Select one card.
![image](https://user-images.githubusercontent.com/66217856/135936507-ee7a52c4-abdd-42a6-82a1-173b3d503b86.png)
2. Select another card.
![image](https://user-images.githubusercontent.com/66217856/135936526-a7fa6d82-547a-4434-a173-c9f7773c90f9.png)
3. In some cases subtraction causes negative numbers. In this case, I will divide and get a number that... doesn't quite exist in cards. The result; after dividing? Check it out:
![image](https://user-images.githubusercontent.com/66217856/135936633-66d6e2a1-ce77-410a-b0f7-c50714dc746c.png)
Yeah... not quite right.

The big problem? The checking algorithm **counts these as valid steps to a solution!** This means that unreasonable or unintuitive answers **are considered right by the checking algorithm!**

**Comment by ericx1e** [comment]
Decimals are a part of the game! They are unintuitive, but finding a solution with them is the fun part.
